### ISSUE TITLE
Please i need helper_3dmath with function 

### ISSUE THREAD

**Issue by martin52** [LucvW/PositioningTIPS#1]
Hello, I am a student from Argentina, and I was looking at your thesis, but when I wanted to implement it in my project, I noticed that the functions in the helper_3dmath.h library are missing. 
Please share the functions:
VectorInt16 :: getVectorFloat ()
VectorFloat :: getAddition ()
VectorFloat :: getQuat ()
Thank you so much, you're great
 :) 8)

Or send me an email with the project 
email:  daniel.boullon@hotmail.es

**Comment by williamtmurray** [comment]
Hi,
Great work on this project and thesis. I am having the same issue with the following:
VectorInt16 :: getVectorFloat ()
VectorFloat :: getAddition ()
VectorFloat :: getQuat ()
Also, J Rowberg does not have any libraries called MPU9250, only MPU6050 and MPU9150. I'm wondering if you made your own by modifying their header files?
Any help would be greatly appreciated. I can also supply my email for contact.
Thanks!

**Comment by LucvW** [comment]
Hi,
Thanks for your comments! It has been some time ago and I also am not able to find the MPU9250 library of J Rowberg again. The files were not edited for as far as I remember, but I will add them to the library just in case. 
The 3D math helper functions that you are missing are given below and can be added to your projects. 

`
VectorFloat getVectorFloat(){ // simple coversion from the int version to the float version of a vector
          VectorFloat r(x,y,z);
          r.x = x;
          r.y = y;
          r.z = z;
          return r; 
        }
`
`
VectorFloat getAddition(VectorFloat p){ // simple addition on each parameter
            VectorFloat r(x,y,z);
            r.x = x+p.x;
            r.y = y+p.y;
            r.z = z+p.z;
            return r;
        }
`
`
Quaternion getQuat(){ // Converting vector to quaternion
          Quaternion q(w, x, y, z);
          float degtorad = 3.14159 / 180;
          x = x*degtorad;
          y = y*degtorad;
          z = z*degtorad;          
          q.w = cos(x/2) * cos(y/2) * cos(z/2) + sin(x/2) * sin(y/2) * sin(z/2);
          q.x = sin(x/2) * cos(y/2) * cos(z/2) - cos(x/2) * sin(y/2) * sin(z/2);
          q.y = cos(x/2) * sin(y/2) * cos(z/2) + sin(x/2) * cos(y/2) * sin(z/2);
          q.z = cos(x/2) * cos(y/2) * sin(z/2) - sin(x/2) * sin(y/2) * cos(z/2);
          return q;
        }
`

Hope this will help you on your way!

**Comment by dientucamranh** [comment]
how to use your code?
