### ISSUE TITLE
NOISE PARAMETERS and LPF concerns

### ISSUE THREAD

**Issue by mrrobles09** [LucvW/PositioningTIPS#2]
Sorry making a fuzz out of this. I am currently researching about linear acceleration and its position using MPU9250 and I notice some constant in your codes that quite get my curiosity especially in noise filter variables and your alpha in low pass filter.

**NOISE PARAMETERS OF THE SENSORS**

![constants](https://user-images.githubusercontent.com/32480279/31117710-621e2034-a85d-11e7-8e31-df4f8bd4686b.JPG)

**LOW PASS FILTER (alpha)**

![alpha](https://user-images.githubusercontent.com/32480279/31117853-f1f1fe60-a85d-11e7-9f5b-580d169151d2.JPG)

My question is how did you get those values especially NPL which is 0.025 and alpha = 0.05?
I've read your document about noise filter but this only explains the code itself on how the NF works and not the math behind it.

Can you shed some light on this? thanks

**Comment by LucvW** [comment]
Sorry to leave you in the dark, but I honestly do not remember the exact reason these parameters were chosen. The project we did was not focussed on this point, and the current values were found once and worked for the project goal.
