### ISSUE TITLE
Unstable result position

### ISSUE THREAD

**Issue by radleypr** [LucvW/PositioningTIPS#5]
Hi, the code finally compiles and after running the code I get this kind of result : 

DMP ready! Push button to start
startStream
xpos:0.9485351562
ypos:1.0445332527
zpos:5.0065522193
xnor:0.0105566298
ynor:-0.0122900903
znor:0.9998683929
xpos:0.7573284626
ypos:1.2099733352
zpos:19.8928356170
xnor:0.0100881946
ynor:-0.0117513644
znor:0.9998794555
xpos:0.4325145244
ypos:1.4909924507
zpos:45.1827621459
xnor:0.0096478691
ynor:-0.0100270318
znor:0.9999025344
xpos:-0.0333349704
ypos:1.8940107345
zpos:81.4563980102
xnor:0.0092392683
ynor:-0.0084593658
znor:0.9999206542
xpos:-0.6197401046
ypos:2.4013166427
zpos:127.1201629638
xnor:0.0088472061
ynor:-0.0070203924
znor:0.9999350547
xpos:-1.3206466436
ypos:3.0076794624
zpos:181.7037048339
xnor:0.0084774255
ynor:-0.0057334208
znor:0.9999461174
xpos:-2.1304430961
ypos:3.7082524299
zpos:244.7709808349
xnor:0.0081310091
ynor:-0.0045753898
znor:0.9999545097
xpos:-3.0504689216
ypos:4.5042047500
zpos:316.4274902343
xnor:0.0078018312
ynor:-0.0035360083
znor:0.9999609947
xpos:-4.0686616897
ypos:5.3851103782
zpos:395.7343139648
xnor:0.0074947748
ynor:-0.0025915954
znor:0.9999661445
xpos:-5.1802029609
ypos:6.3468112945
zpos:482.3167724609
xnor:0.0072041339
ynor:-0.0017501838
znor:0.9999698638
xpos:-6.3803343772
ypos:7.3852014541
zpos:575.8048095703
xnor:0.0069382772
ynor:-0.0009883746
znor:0.9999722480
xpos:-7.6722149848
ypos:8.5030288696
zpos:676.4454345703
xnor:0.0066900916
ynor:-0.0003076782
znor:0.9999740600
xpos:-9.0440950393
ypos:9.6901359558
zpos:783.3234252929
xnor:0.0064706735
ynor:0.0003108500
znor:0.9999751091
xpos:-10.4920158386
ypos:10.9431056976
zpos:896.1306152343
xnor:0.0062746343
ynor:0.0008611318
znor:0.9999753952
xpos:-12.0123176574
ypos:12.2587833404
zpos:1014.5822753906
xnor:0.0060862708
ynor:0.0013456554
znor:0.9999757766
xpos:-13.6059589385
ypos:13.6380138397
zpos:1138.7536621093
xnor:0.0059103202
ynor:0.0017787754
znor:0.9999760627
xpos:-15.2649774551
ypos:15.0739097595
zpos:1268.0242919921
xnor:0.0057370853
ynor:0.0021669983
znor:0.9999758720
xpos:-16.9861316680
ypos:16.5636749267
zpos:1402.1417236328
xnor:0.0055714554
ynor:0.0025027368
znor:0.9999757766
xpos:-18.7663631439
ypos:18.1046714782
zpos:1540.8677978515
xnor:0.0054141302
ynor:0.0028058530
znor:0.9999755859
xpos:-20.6063308715
ypos:19.6974830627
zpos:1684.2542724609
xnor:0.0052632803
ynor:0.0030750966
znor:0.9999752998
xpos:-22.4995212554
ypos:21.3364734649
zpos:1831.7932128906
xnor:0.0051153187
ynor:0.0033181929
znor:0.9999750137
xpos:-24.4433078765
ypos:23.0193767547
zpos:1983.2802734375
xnor:0.0049696192
ynor:0.0035369706
znor:0.9999747276
xpos:-26.4351596832
ypos:24.7440052032
zpos:2138.5180664062
xnor:0.0048276944
ynor:0.0037328882
znor:0.9999744415
xpos:-28.4756431579
ypos:26.5108661651
zpos:2297.5510253906
xnor:0.0046954350
ynor:0.0039059743
znor:0.9999739646
xpos:-30.5594863891
ypos:28.3153915405
zpos:2459.9680175781
xnor:0.0045706372
ynor:0.0040565805
znor:0.9999734878
xpos:-32.6845245361
ypos:30.1557121276
zpos:2625.6003417968
xnor:0.0044504780
ynor:0.0041826338
znor:0.9999733924
xpos:-34.8487625122
ypos:32.0301055908
zpos:2794.2924804687
xnor:0.0043417744
ynor:0.0042990131
znor:0.9999733924
xpos:-37.0517616271
ypos:33.9381980895
zpos:2966.0104980468
xnor:0.0042429790
ynor:0.0043980860
znor:0.9999732017
xpos:-39.2901191711
ypos:35.8770408630
zpos:3140.4887695312
xnor:0.0041519479
ynor:0.0044822902
znor:0.9999729156
xpos:-41.5620880126
ypos:37.8451232910
zpos:3317.5908203125
xnor:0.0040685873
ynor:0.0045548419
znor:0.9999727249
xpos:-43.8659591674
ypos:39.8409690856
zpos:3497.1838378906
xnor:0.0039938734
ynor:0.0046184625
znor:0.9999725341
xpos:-46.2021522521
ypos:41.8649482727
zpos:3679.3005371093
xnor:0.0039226972
ynor:0.0046777591
znor:0.9999722480
xpos:-48.5671501159
ypos:43.9140090942
zpos:3863.6662597656
xnor:0.0038454998
ynor:0.0047378196
znor:0.9999718666
xpos:-50.9595375061
ypos:45.9869270324
zpos:4050.1706542968
xnor:0.0037745223
ynor:0.0047967228
znor:0.9999714851
xpos:-53.3779258728
ypos:48.0824966430
zpos:4238.7050781250
xnor:0.0037144420
ynor:0.0048450903
znor:0.9999714851
xpos:-55.8226127624
ypos:50.2009887695
zpos:4429.2934570312
xnor:0.0036402688
ynor:0.0048921723
znor:0.9999713897
xpos:-58.2907562255
ypos:52.3399276733
zpos:4621.7133789062
xnor:0.0035665936
ynor:0.0049340701
znor:0.9999712944
xpos:-60.7811813354
ypos:54.4982986450
zpos:4815.8735351562
xnor:0.0034895009
ynor:0.0049634690
znor:0.9999709129
xpos:-63.2927703857
ypos:56.6751365661
zpos:5011.6865234375
xnor:0.0034154386
ynor:0.0049886031
znor:0.9999706268
xpos:-65.8258132934
ypos:58.8706970214
zpos:5209.1752929687
xnor:0.0033456010
ynor:0.0050046300
znor:0.9999703407
xpos:-68.3779602050
ypos:61.0829353332
zpos:5408.1562500000
xnor:0.0032760291
ynor:0.0050164771
znor:0.9999698638
xpos:-70.9482421875
ypos:63.3110122680
zpos:5608.5537109375
xnor:0.0032079455
ynor:0.0050275926
znor:0.9999695777
xpos:-73.5357894897
ypos:65.5541610717
zpos:5810.2993164062
xnor:0.0031303629
ynor:0.0050306682
znor:0.9999691963
xpos:-76.1404190063
ypos:67.8122253417
zpos:6013.3789062500
xnor:0.0031181340
ynor:0.0032016036
znor:0.9999763488
xpos:-78.7605819702
ypos:70.0838394165
zpos:6217.6723632812
xnor:0.0030635538
ynor:0.0033812582
znor:0.9999757766
xpos:-81.3955078125
ypos:72.3683242797
zpos:6423.1191406250
xnor:0.0030029296
ynor:0.0035288076
znor:0.9999752044
xpos:-84.0444869995
ypos:74.6650619506
zpos:6629.6635742187
xnor:0.0029425945
ynor:0.0036611232
znor:0.9999744415
xpos:-86.7077102661
ypos:76.9742202758
zpos:6837.3208007812
xnor:0.0028885496
ynor:0.0037711615
znor:0.9999738693
xpos:-89.3836135864
ypos:79.2944412231
zpos:7045.9687500000
xnor:0.0028449559
ynor:0.0038766500
znor:0.9999731063
xpos:-92.0715560913
ypos:81.6251678466
zpos:7255.5576171875
xnor:0.0028120274
ynor:0.0039744038
znor:0.9999722480
xpos:-94.7709426879
ypos:83.9658813476
zpos:7466.0405273437
xnor:0.0027842700
ynor:0.0040669770
znor:0.9999714851
xpos:-97.4819107055
ypos:86.3167037963
zpos:7677.4282226562
xnor:0.0027563321
ynor:0.0041468629
znor:0.9999708175
xpos:-100.2032165527
ypos:88.6765518188
zpos:7889.6230468750
xnor:0.0027166497
ynor:0.0042185616
znor:0.9999706268
xpos:-102.9343566894
ypos:91.0449829101
zpos:8102.5864257812
xnor:0.0026762723
ynor:0.0042696647
znor:0.9999702453
xpos:-105.6748352050
ypos:93.4215698242
zpos:8316.2792968750
xnor:0.0026324815
ynor:0.0043181672
znor:0.9999696731
xpos:-108.4247741699
ypos:95.8064270019
zpos:8530.7109375000
xnor:0.0025846445
ynor:0.0043607192
znor:0.9999691963
xpos:-111.1831359863
ypos:98.1986465454
zpos:8745.8007812500
xnor:0.0025431027
ynor:0.0044149880
znor:0.9999687194
xpos:-113.9495010375
ypos:100.5978622436
zpos:8961.5156250000
xnor:0.0025045869
ynor:0.0044643707
znor:0.9999681472
xpos:-116.7234649658
ypos:103.0037231445
zpos:9177.8242187500
xnor:0.0024782297
ynor:0.0044945135
znor:0.9999680519
xpos:-119.5049743652
ypos:105.4161834716
zpos:9394.7216796875
xnor:0.0024583249
ynor:0.0045256094
znor:0.9999678611
xpos:-122.2933578491
ypos:107.8346633911
zpos:9612.1562500000
xnor:0.0024388079
ynor:0.0045580987
znor:0.9999675750
xpos:-125.0882644653
ypos:110.2588577270
zpos:9830.1005859375
xnor:0.0024223711
ynor:0.0045979256
znor:0.9999670982
xpos:-127.8893814086
ypos:112.6884841918
zpos:10048.5292968750
xnor:0.0024082112
ynor:0.0046335191
znor:0.9999666213
xpos:-130.6967926025
ypos:115.1236267089
zpos:10267.4492187500
xnor:0.0023845937
ynor:0.0046725974
znor:0.9999663352
xpos:-133.5098114013
ypos:117.5636825561
zpos:10486.8066406250
xnor:0.0023680946
ynor:0.0047099142
znor:0.9999659538
xpos:-136.3281555175
ypos:120.0084075927
zpos:10706.5800781250
xnor:0.0023361351
ynor:0.0047474908
znor:0.9999658584
xpos:-139.1515655517
ypos:122.4575805664
zpos:10926.7490234375
xnor:0.0023109970
ynor:0.0047884674
znor:0.9999654769
xpos:-141.9799804687
ypos:124.9111480712
zpos:11147.3095703125
xnor:0.0022838876
ynor:0.0048237271
znor:0.9999647140
stopStream

I would like to ask why the value of the position keeps adding very quickly ? In addition, could you elaborate a little bit on the xnor, ynor and znor because from reading the code, it seems like a starting position, but from the paper it is an orientation of the probe. 

Thank you

**Comment by LucvW** [comment]
Hi radleypr,

Great that you got the code running! Unfortunately, determining position using only accelerometers (or other parts of th MPU) was not successful. There is too much jitter and drift with the available computation power and methods used. This is why the position keeps moving to enormous numbers. In the paper this conclusion is also drawn from similar results that you found.
The x,y,z-nor values are normalized values of the orientation, thus the squared sum accounts to 1.
If you are looking to do position determination, I would recommend using a setup that can provide a reference by cameras or known distances. For orientation determination alone the device should suffice.

Best of luck
